-- MCSR Offline / Supabase baseline schema
-- Apply this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create or replace function public.mcsroff_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 32),
  elo integer not null default 1200 check (elo >= 0),
  rank_tier text not null default 'Unranked',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  state text not null check (
    state in (
      'queueing',
      'matched',
      'world_generating',
      'world_generated',
      'countdown',
      'running',
      'finished',
      'aborted'
    )
  ),
  seed_mode text not null check (seed_mode in ('MATCH', 'PRACTICE')),
  seed_type_label text not null,
  filter_ids jsonb not null default '[]'::jsonb,
  seed text,
  fsg_filter_id text,
  fsg_token text,
  countdown_target timestamptz,
  winner_player_id uuid references auth.users(id) on delete set null,
  abort_reason text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.match_players (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches(id) on delete cascade,
  player_id uuid not null references auth.users(id) on delete cascade,
  slot text not null check (slot in ('host', 'opponent')),
  display_name text not null,
  elo_snapshot integer not null default 1200 check (elo_snapshot >= 0),
  rank_snapshot text not null default 'Unranked',
  connected boolean not null default true,
  world_status text not null default 'queued' check (
    world_status in ('queued', 'generating', 'generated', 'ready', 'running', 'finished', 'disconnected')
  ),
  ready_at timestamptz,
  finished_at timestamptz,
  finish_time_ms bigint,
  result text check (result in ('win', 'loss', 'forfeit', 'disconnect')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint match_players_unique_match_player unique (match_id, player_id),
  constraint match_players_unique_match_slot unique (match_id, slot)
);

create table if not exists public.queue_entries (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null unique references auth.users(id) on delete cascade,
  seed_mode text not null check (seed_mode in ('MATCH', 'PRACTICE')),
  seed_type_label text not null,
  filter_ids jsonb not null default '[]'::jsonb,
  status text not null default 'searching' check (status in ('searching', 'matched', 'cancelled')),
  claimed_match_id uuid references public.matches(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null default (timezone('utc', now()) + interval '2 minutes')
);

create table if not exists public.match_events (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.matches(id) on delete cascade,
  player_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_matches_state on public.matches(state, updated_at desc);
create index if not exists idx_match_players_match_id on public.match_players(match_id);
create index if not exists idx_match_players_player_id on public.match_players(player_id);
create index if not exists idx_queue_entries_status_created_at on public.queue_entries(status, created_at);
create index if not exists idx_queue_entries_expires_at on public.queue_entries(expires_at);
create index if not exists idx_match_events_match_id on public.match_events(match_id, created_at desc);

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.mcsroff_set_updated_at();

drop trigger if exists trg_matches_updated_at on public.matches;
create trigger trg_matches_updated_at
before update on public.matches
for each row execute function public.mcsroff_set_updated_at();

drop trigger if exists trg_match_players_updated_at on public.match_players;
create trigger trg_match_players_updated_at
before update on public.match_players
for each row execute function public.mcsroff_set_updated_at();

drop trigger if exists trg_queue_entries_updated_at on public.queue_entries;
create trigger trg_queue_entries_updated_at
before update on public.queue_entries
for each row execute function public.mcsroff_set_updated_at();

alter table public.profiles enable row level security;
alter table public.matches enable row level security;
alter table public.match_players enable row level security;
alter table public.queue_entries enable row level security;
alter table public.match_events enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists queue_entries_select_own on public.queue_entries;
create policy queue_entries_select_own
on public.queue_entries
for select
to authenticated
using (auth.uid() = player_id);

drop policy if exists queue_entries_insert_own on public.queue_entries;
create policy queue_entries_insert_own
on public.queue_entries
for insert
to authenticated
with check (auth.uid() = player_id);

drop policy if exists queue_entries_update_own on public.queue_entries;
create policy queue_entries_update_own
on public.queue_entries
for update
to authenticated
using (auth.uid() = player_id)
with check (auth.uid() = player_id);

drop policy if exists queue_entries_delete_own on public.queue_entries;
create policy queue_entries_delete_own
on public.queue_entries
for delete
to authenticated
using (auth.uid() = player_id);

drop policy if exists matches_select_participant on public.matches;
create policy matches_select_participant
on public.matches
for select
to authenticated
using (
  exists (
    select 1
    from public.match_players mp
    where mp.match_id = matches.id
      and mp.player_id = auth.uid()
  )
);

drop policy if exists match_players_select_participant on public.match_players;
create policy match_players_select_participant
on public.match_players
for select
to authenticated
using (
  exists (
    select 1
    from public.match_players own_mp
    where own_mp.match_id = match_players.match_id
      and own_mp.player_id = auth.uid()
  )
);

drop policy if exists match_players_update_self on public.match_players;
create policy match_players_update_self
on public.match_players
for update
to authenticated
using (player_id = auth.uid())
with check (player_id = auth.uid());

drop policy if exists match_events_select_participant on public.match_events;
create policy match_events_select_participant
on public.match_events
for select
to authenticated
using (
  exists (
    select 1
    from public.match_players mp
    where mp.match_id = match_events.match_id
      and mp.player_id = auth.uid()
  )
);

comment on table public.matches is 'Top-level match state. Edge Functions should own writes to seed assignment and countdown target.';
comment on table public.match_players is 'Per-player state within a match. Clients may update only their own row.';
comment on table public.queue_entries is 'Matchmaking queue. Queue claims should happen in Edge Functions using service role.';
